name: build-and-test

on:
  push:
    # all branches
    paths-ignore:
      - 'documentation/**'
  pull_request:
    paths-ignore:
      - 'documentation/**'

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Open Dylan
        uses: dylan-lang/install-opendylan@v3

      - name: Install dependencies
        run: deft update

      - name: Build and Run Tests
        run: deft test -- --report surefire --report-file _build/test-output.xml

      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: '**/_build/test-output.xml'
